### ISSUE TITLE
Some updates for the front-end and back-end

### ISSUE THREAD

**Issue by SaberDoTcodeR** [oxydev/SubsCrypt-ink#14]
- [x] Providers data getter function should be added ( getting plan info )
- [x] Provider login passphrase mechanism
- [x] Data of total subscription and providers in the contract for showing
- [x] Events should be added
- [x] Subscription renew functionality should be implemented
- [ ]  Add tests for the codes of this issue

**Comment by HadiEsna** [comment]
>  Data of total subscription and providers in the contract for showing

will be handled by events

**Comment by SaberDoTcodeR** [comment]
renew test are added in this [commit](https://github.com/oxydev/SubsCrypt-ink/commit/926d4dc380d97d95854f88e5919b2700b7f6f685)
